language: rust

sudo: required

dist: trusty

install:
  - curl https://static.rust-lang.org/rustup.sh |
    sh -s -- --add-target=$TARGET --disable-sudo -y --prefix=`rustc --print sysroot`

script:
  - cargo build
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      sh ci/run-docker.sh $TARGET;
    else
      export CARGO_TARGET_DIR=`pwd`/target;
      sh ci/run.sh $TARGET;
    fi

cache: cargo

matrix:
  include:

    # Test compatibility
    #
    # 1.15.0 is the oldest supported version of Rust. This value should NOT be changed
    - os: linux
      rust: 1.15.0
      script:
        - cargo test
      install:

    # Test on latest stable
    - os: linux
      rust: stable
      script:
        - cargo test
      install:

    # OS X
    - os: osx
      rust: stable
      script:
        - cargo test
      install:

    # iOS
    - os: osx
      osx_image: xcode8.2
      env: TARGET=x86_64-apple-ios
      rust: stable

    # Android
    - os: linux
      env: TARGET=arm-linux-androideabi
      rust: stable

notifications:
  email:
    on_success: never
