language: rust
rust:
    - stable
    - beta

sudo: required

dist: bionic

install:
  - curl https://static.rust-lang.org/rustup.sh |
    sh -s -- --add-target=$TARGET --disable-sudo -y --prefix=`rustc --print sysroot`

script:
  - cargo build --verbose
  - cargo test --verbose

cache: cargo

matrix:
  include:

    # Test compatibility
    #
    # 1.36.0 is the oldest supported version of Rust. This value should NOT be changed
    - os: linux
      rust: 1.36.0

    # Test on linux
    - os: linux

    # OS X
    - os: osx

    # iOS
    - os: osx
      osx_image: xcode11
      env: TARGET=aarch64-apple-ios

    - os: linux
      env: TARGET=arm-linux-androideabi

    - os: linux
      env: TARGET=aarch64-linux-android

    - os: linux
      env: TARGET=X86_64-linux-android

notifications:
  email:
    on_success: never
