[package]
authors = ["Olivier Yiptong <olivier@olivieryiptong.com>"]
name = "hull"
version = "0.1.0"

[dependencies]
env_logger = "0.3.5"
log = "0.3.6"
rustfmt = "0.6.3"
serde = "0.9.6"
serde_derive = "0.9.6"
serde_json = "0.9.5"
time = "0.1.35"

[dev-dependencies]
tempdir = "0.3.5"
